server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    gzip on;
    gzip_types text/css application/javascript application/json;
    client_max_body_size 55M;
}
